name: Github Workflow Validator

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/*"
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install action-validator with asdf
        uses: asdf-vm/actions/install@v3
        with:
          tool_versions: |
            action-validator 0.5.4
      - name: Lint Actions
        continue-on-error: true
        id: validator
        run: |
          ISSUES=$(cat << EOF
          `action-validator .github/workflows/* 2>&1`
          EOF
          )
          echo "ISSUES<<EOF" >> "$GITHUB_OUTPUT"
          echo "$ISSUES" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
      - name: Comment workflow validator results
        uses: thollander/actions-comment-pull-request@v2
        if:  ${{ (github.ref != 'refs/heads/main') }}
        with:
          message: |
            ```
            ${{ steps.validator.outputs.issues }}
            ```
          comment_tag: validator
